### ISSUE TITLE
[Config] Improve Gruntfile for SASS

### ISSUE THREAD

**Issue by Anicky** [Anicky/Curvation#16]
Actually, Gruntfile.js has this line :

``` javascript
'public/css/curvation.min.css': 'src/sass/curvation.scss'
```

This has to be changed in order to do this task for every file in "src/sass" folder.
Also, "src/css" doesn't exist anymore, so there are some lines to clean/change in Gruntfile.js

**Comment by AlexiZ** [comment]
Already did it, you can close that issue.
