### ISSUE TITLE
[Player] Ajout de trous pour les snakes

### ISSUE THREAD

**Issue by Anicky** [Anicky/Curvation#2]
Créer des trous dans les snakes selon des probabilités.

**Comment by smourph** [comment]
Résolu avec les commits 0685ee3bd5ebaa56e92ca8571b11ff9a4e4269b4 et 2b5c48d506c8bfa8a3363c778b42383d76eb4c77

**Comment by Anicky** [comment]
Pour moi il y a encore une amélioration à faire car pendant le trou, on ne voit pas le point où on se trouve. C'est un peu perturbant : on disparait totalement pendant un instant. Il faudrait plutot que l'on continue à voir le point où on est, sans laisser de trace. Ca implique de garder un historique du point précédent, et qu'on l'efface (essais non concluants pour le moment, si quelqu'un veut essayer...)

**Comment by smourph** [comment]
J'ai fait les mêmes essais non concluant (la difference entre lastX et x est trop petite, les pixels se chevauchent), mais je pensais faire une autre request juste pour ça.

**Comment by Anicky** [comment]
Ok je te laisse la créer !
