### ISSUE TITLE
[Player] Le snake doit rester visible pendant les trous

### ISSUE THREAD

**Issue by smourph** [Anicky/Curvation#4]
Pendant les trous, nous perdons la position du snake et nous devons jouer à l'aveugle. Il faudrait permettre au snake de continuer à s'afficher sans qu'il ne laisse de derrière lui.

**Comment by Anicky** [comment]
Une idée possible est de créer un cercle à la précédente position, et de l'effacer. Il y a la fonction clip() du canvas qui permet de restreindre une partie du canvas. Puis on efface tout le canvas, mais du coup seul ce qui aura été fait avant le clip() sera affecté : on effacera donc seulement le point précédent.

```
Player.prototype.draw = function (interpolationPercentage) {
    if(this.currentHole) {
        context.save();
        context.beginPath();
        context.arc(this.lastX, this.lastY, this.size, 0, 2 * Math.PI);
        context.clip();
        context.clearRect(0, 0, canvas.width, canvas.height);
        context.restore();
    }
    var x = this.lastX + (this.x - this.lastX) * interpolationPercentage;
    var y = this.lastY + (this.y - this.lastY) * interpolationPercentage;
    context.fillStyle = this.color;
    context.beginPath();
    context.arc(x, y, this.size, 0, 2 * Math.PI);
    context.fill();
};
```

Plusieurs problèmes :
- La taille du cercle que l'on efface ne suffit pas, il faut faire un this.size*2 pour avoir des bons résultats...J'ai aussi essayé en sauvegardant un autre lastX et lastY (donc deux positions précédentes), en créant les deux positions et en les effaçant. Là encore il faut faire un this.size+1 pour que ce soit efficace.
- Le plus gros problème : le fait de faire un clearRect() va effacer les points précédents...Mais aussi tout ce qu'il y avait sur le canvas à cet endroit là ! Ca veut dire que si on rentre dans un joueur, mais que le trou se fait à cet endroit, et qu'on arrive à passer par-dessus lui, ça va aussi effacer une partie de son trait.

Le dernier point montre que le système de déplacement, affichage et collisions n'est pas parfait...Le fait de regarder si le pixel courant a une opacité a déjà montré une faiblesse lorsqu'on ralentit la vitesse du snake : celui-ci étant un cercle de plusieurs pixels de rayon, en allant trop lentement, il se "rencontre" lui-même et cela provoque la collision.
Il faut peut-être revenir à un tableau de positions X,Y occupées et comparer la position actuelle du joueur avec celles-ci...(Le problème là encore c'est les X et Y qui ne sont pas des nombres entiers)
