### ISSUE TITLE
[Project] Mise en place d'un Grunt

### ISSUE THREAD

**Issue by smourph** [Anicky/Curvation#7]
Je propose de mettre en place un Grunt pour la suite du projet (formation aux nouveaux outils, tout ça...).
On peut commencer par lui faire générer un curvation.min.js... ;)

Il faudra dans ce cas peut-être commencer un Readme et y insérer les commandes d'installation des pré-requis (Node et Grunt...).

**Comment by Anicky** [comment]
Et si tu peux nous faire ensuite une petite explication/démo de comment t'as fait, ça m'intéresse :)

**Comment by smourph** [comment]
J'ai mis à jour le README.md pour intégrer les commandes que j'ai créé dans Grunt.js.
Je pourrais vous faire une démo plus détaillée à la pause de midi.

**Comment by smourph** [comment]
Arf il manquait une info nécessaire dans le README concernant l'installation de grunt-cli (sinon grunt ne fonctionne pas). Je m'excuse pour les multiples commit, j'ai dû faire les modifs avec mon téléphone pour que vous puissez avoir l'info rapidement.

Comme grunt-cli est généralement installé de manière globale (npm install -g), je n'ai pas intégré grunt-cli dans le package.json qui permet d'installer automatiquement les autres dépendances. Il faut donc l'installer manuellement au préalable, comme indiqué dans le README :
npm install -g grunt-cli
PUIS
npm install
